spring.application.name=SpringBoot_Backend
server.port=${PORT:8080}
spring.datasource.url=mysql://root:exBRsnngTAWVogsCQKGtBTxGpGsQxJrY@mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=exBRsnngTAWVogsCQKGtBTxGpGsQxJrY
spring.datasource.driverClass=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
