spring.application.name=SpringBoot_Backend
server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://root:exBRsnngTAWVogsCQKGtBTxGpGsQxJrY@crossover.proxy.rlwy.net:58532/railway
spring.datasource.username=root
spring.datasource.password=exBRsnngTAWVogsCQKGtBTxGpGsQxJrY
spring.datasource.driverClass=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
